version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: lexguardian-postgres
    environment:
      POSTGRES_USER: lexguard
      POSTGRES_PASSWORD: lexguard
      POSTGRES_DB: lexguardian
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database_setup_postgresql.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: lexguardian-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: lexguardian-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: lexguardian-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  pgdata:
  redisdata:
  miniodata:


